### ISSUE TITLE
你的思维导图用的什么工具，非常的Q，求推荐！

### ISSUE THREAD

**Issue by baininghan** [sunseekers/Vue#1]
如题，如果有时间请更新一下README中出现的多处错别字！^_^

**Comment by lpf260** [comment]
同求

**Comment by Jancd** [comment]
@lpf260 @baininghan 同求 + 1

**Comment by sunseekers** [comment]
> 如题，如果有时间请更新一下README中出现的多处错别字！^_^

谢谢关注，有时间把更新一下，把在工作常用的，遇到的坑也补上

**Comment by sunseekers** [comment]
[戳这里](https://www.processon.com/)   思维导图工具

**Comment by sunseekers** [comment]
@Jancd @baininghan @lpf260 谢谢关注，有时间把更新一下，把在工作常用的，遇到的坑也补上

---

[戳这里](https://www.processon.com/) 思维导图工具

**Comment by qiutian00** [comment]
:+1::+1:，又有机会学习了，:blush:
