### ISSUE TITLE
vue

### ISSUE THREAD

**Issue by fatemeataee** [sunseekers/Vue#7]
Hello, your explanation is so perfect and so useful for me to understand how vue works.
by the way i want to ask you do you can make your explanation type them in **English**; i think the _most people can use your nice describe._

thanks alot for your attention ;)

**Comment by sunseekers** [comment]
> Hello, your explanation is so perfect and so useful for me to understand how vue works.
> by the way i want to ask you do you can make your explanation type them in **English**; i think the _most people can use your nice describe._
> 
> thanks alot for your attention ;)

very high heart, it is helpful for your understanding ,please note the source when translating than you

**Comment by sunseekers** [comment]
> Hello, your explanation is so perfect and so useful for me to understand how vue works.
> by the way i want to ask you do you can make your explanation type them in **English**; i think the _most people can use your nice describe._
> 
> thanks alot for your attention ;)

very high heart, it is helpful for your understanding ,please note the source when translating thank you
